#!/bin/bash

panic() {
    echo "$1"
    exit 1
}

files=()
len=$#
for ((i=1;i<=len;i++)); do
    arg="${!i}"
    case "$arg" in
        -o|--output)
            if [ "$i" -eq "$len" ]; then
                panic "$arg requires an argument"
            else
                let i++
                out="${!i}"
            fi;;
        *)
            [ -f "$arg" ] || panic "$arg does not exist"
            files+=("$arg")
            ;;
    esac
done

[ -n "$out" ] && mkdir -p "$out"
[ "${#files[@]}" -eq 0 ] && exit 0

for file in "${files[@]}"; do
    IFS=. read -a xs <<< "$file"
    len="${#xs[@]}"
    [ "$len" -lt 2 ] && panic "$file does not have a file extension"

    case "${xs[-1]}" in
        bz2)
            if [ "$len" -gt 2 ] && [ "${xs[-2]}" == tar ]; then
                if [ -z "$out" ]; then
                    tar xfj "$file"
                else
                    tar xfj "$file" -C "$out"
                fi
            else
                [ -n "$out" ] && echo "bzip2 does not support changing output directory"
                bzip2 -d "$file"
            fi;;
        gz)
            if [ "$len" -gt 2 ] && [ "${xs[-2]}" == tar ]; then
                if [ -z "$out" ]; then
                    tar xfz "$file"
                else
                    tar xfz "$file" -C "$out"
                fi
            else
                [ -n "$out" ] && echo "gzip does not support changing output directory"
                gzip -d "$file"
            fi;;
        tar)
            if [ -z "$out" ]; then
                tar xf "$file"
            else
                tar xf "$file" -C "$out"
            fi;;
        tbz2)
            if [ -z "$out" ]; then
                tar xfj "$file"
            else
                tar xfj "$file" -C "$out"
            fi;;
        tgz)
            if [ -z "$out" ]; then
                tar xfz "$file"
            else
                tar xfz "$file" -C "$out"
            fi;;
        txz)
            if [ -z "$out" ]; then
                tar xfJ "$file"
            else
                tar xfJ "$file" -C "$out"
            fi;;
        xz)
            if [ "$len" -gt 2 ] && [ "${xs[-2]}" == tar ]; then
                if [ -z "$out" ]; then
                    tar xfJ "$file"
                else
                    tar xfJ "$file" -C "$out"
                fi
            else
                [ -n "$out" ] && echo "xz does not support changing output directory"
                xz -d "$file"
            fi;;
        zip)
            if [ -z "$out" ]; then
                unzip "$file"
            else
                unzip "$file" -d "$out"
            fi;;
    esac
done
